<script setup>
import UiPageHeader from '../../components/ui/UiPageHeader.vue'
import UiEmptyState from '../../components/ui/UiEmptyState.vue'
import UiDataTable from '../../components/ui/UiDataTable.vue'
defineProps({matches:{type:Array,default:()=>[]},preseason:{type:Object,default:()=>({})},marketPeriod:{type:Object,default:()=>({})},calendarState:{type:Object,default:()=>({})},formatDate:{type:Function,required:true}})
const emit=defineEmits(['open-match','open-team'])
</script>
<template>
<section class="screen-grid calendar-screen modern-r7">
  <article class="football-panel calendar-main"><UiPageHeader eyebrow="AGENDA DEPORTIVA" title="Calendario" description="Últimos resultados y próximos compromisos, con el estado que afecta al siguiente paso de la carrera." :status="calendarState.label || (preseason.active?'Pretemporada':'Temporada oficial')" />
    <UiDataTable v-if="matches.length" class="calendar-modern" aria-label="Partidos de la carrera" sticky><table><thead><tr><th>Fecha</th><th>Rival</th><th>Sede</th><th>Competición</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="m in matches" :key="m.id||m.date+m.opponent" :class="{played:m.played}"><td><b>{{m.raw_date?formatDate(m.raw_date):m.date}}</b></td><td><button v-if="m.opponent_id" type="button" class="entity-link calendar-team-link" @click="emit('open-team',m.opponent_id)">{{m.opponent}}</button><strong v-else>{{m.opponent}}</strong></td><td>{{m.venue}}</td><td>{{m.competition}}</td><td><em>{{m.status}}</em></td><td><button type="button" class="text-action" @click="emit('open-match',m)">Ver partido →</button></td></tr></tbody></table></UiDataTable>
    <UiEmptyState v-else :title="calendarState.label || 'Sin partido programado'" :detail="calendarState.detail || 'No hay compromisos cargados para este tramo del calendario. Es normal entre fases o mientras se resuelve el siguiente emparejamiento.'" hint="Usa Continuar para avanzar hasta el próximo evento o decisión relevante." /></article>
  <aside class="side-stack"><article class="football-panel rhythm-card"><h2>Ritmo de carrera</h2><div class="week-plan"><div class="plan active"><small>Agenda</small><b>{{calendarState.label || (preseason.active?'Pretemporada':'Temporada oficial')}}</b><p>{{calendarState.detail || (preseason.active?'Continuar avanza como máximo tres días para dar tiempo a fichar, ajustar plantilla y jugar amistosos.':'Continuar salta al siguiente partido o decisión importante.')}}</p><em v-if="calendarState.availability_count">{{calendarState.availability_count}} baja{{Number(calendarState.availability_count)===1?'':'s'}}: {{(calendarState.availability||[]).map(row=>`${row.name} (${row.status})`).join(' · ')}}</em></div><div class="plan"><small>Mercado</small><b>{{marketPeriod.label}}</b><p>{{marketPeriod.open?'Altas e inscripciones disponibles según la regla del país.':'No se tramitan altas hasta el próximo periodo.'}}</p></div><div v-if="preseason.next_friendly" class="plan"><small>Próximo amistoso</small><b>{{formatDate(preseason.next_friendly.date)}}</b><p>{{preseason.next_friendly.home_team}} – {{preseason.next_friendly.away_team}}</p></div></div></article></aside>
</section>
</template>
