<script setup>
defineProps({economy:{type:Object,default:()=>({})},formatMoney:{type:Function,required:true}})
const emit=defineEmits(['open-player'])
</script>
<template>
<section class="screen-grid economy-screen modern-r7">
  <article class="football-panel economy-main">
    <header class="workspace-heading"><div><small>Dirección financiera · Pesetas 1993-94</small><h2>Economía</h2><p>Todas las cantidades están expresadas en pesetas (ptas.). Tesorería y presupuesto de fichajes son magnitudes distintas.</p></div><span class="status-chip" :class="Number(economy.projected_monthly_net||0)>=0?'positive':'negative'">{{economy.status||'—'}}</span></header>
    <div class="economy-kpis modern-kpis"><div class="hero-kpi"><small>Tesorería</small><b>{{formatMoney(economy.cash)}}</b><span>liquidez total</span></div><div><small>Presupuesto fichajes</small><b>{{formatMoney(economy.transfer_budget_remaining)}}</b></div><div><small>Margen transferible</small><b>{{formatMoney(economy.transfer_room)}}</b></div><div><small>Presupuesto salarial / año</small><b>{{formatMoney(economy.wage_budget_annual)}}</b><span>{{Number(economy.wage_budget_usage_pct||0).toFixed(1)}}% comprometido</span></div><div><small>Margen salarial / año</small><b :class="Number(economy.wage_room_annual||0)>0?'good-text':'bad-cell'">{{formatMoney(economy.wage_room_annual)}}</b></div><div><small>Masa salarial / año</small><b>{{formatMoney(economy.annual_wages)}}</b></div><div><small>Balance mensual</small><b :class="Number(economy.projected_monthly_net)>=0?'good-text':'bad-cell'">{{formatMoney(economy.projected_monthly_net)}}</b></div><div><small>Deuda</small><b>{{formatMoney(economy.debt)}}</b></div></div>
    <section class="finance-flow"><h3>Flujo mensual estimado</h3><div><span><small>Socios / abonos</small><b class="good-text">+{{formatMoney(economy.monthly_membership_income)}}</b></span><span><small>TV</small><b class="good-text">+{{formatMoney(economy.monthly_television_income)}}</b></span><span><small>Patrocinio</small><b class="good-text">+{{formatMoney(economy.monthly_sponsorship_income)}}</b></span><span><small>Salarios</small><b class="bad-cell">-{{formatMoney(economy.monthly_wages)}}</b></span><span><small>Operación</small><b class="bad-cell">-{{formatMoney(economy.monthly_operating_expense)}}</b></span><span><small>Intereses</small><b class="bad-cell">-{{formatMoney(economy.monthly_debt_interest)}}</b></span><span><small>Amortización deuda</small><b class="bad-cell">-{{formatMoney(economy.monthly_debt_principal)}}</b></span></div></section>
    <div class="financial-guidance"><strong>Margen prudente · {{economy.health?.label || economy.status || '—'}}</strong><p>Reserva operativa: {{formatMoney(economy.safety_reserve)}}. El margen de fichajes protege esa reserva y cada alta debe caber además en el margen salarial anual. Tener caja no equivale a poder asumir una ficha.</p></div>
    <section v-if="economy.longitudinal?.current_season" class="finance-flow"><h3>{{economy.longitudinal.current_season.season}} · economía acumulada</h3><div><span><small>Socios / abonos</small><b class="good-text">+{{formatMoney(economy.longitudinal.current_season.memberships)}}</b></span><span><small>Taquilla</small><b class="good-text">+{{formatMoney(economy.longitudinal.current_season.gate_receipts)}}</b></span><span><small>TV</small><b class="good-text">+{{formatMoney(economy.longitudinal.current_season.television)}}</b></span><span><small>Patrocinio</small><b class="good-text">+{{formatMoney(economy.longitudinal.current_season.sponsorship)}}</b></span><span><small>Premios</small><b class="good-text">+{{formatMoney(economy.longitudinal.current_season.prize_money)}}</b></span><span><small>Salarios</small><b class="bad-cell">-{{formatMoney(economy.longitudinal.current_season.wages)}}</b></span><span><small>Deuda</small><b class="bad-cell">-{{formatMoney(Number(economy.longitudinal.current_season.debt_interest||0)+Number(economy.longitudinal.current_season.debt_principal||0))}}</b></span><span><small>Traspasos</small><b>{{formatMoney(Number(economy.longitudinal.current_season.transfer_income||0)-Number(economy.longitudinal.current_season.transfer_spend||0))}}</b></span><span><small>Neto acumulado</small><b :class="Number(economy.longitudinal.current_season.net)>=0?'good-text':'bad-cell'">{{formatMoney(economy.longitudinal.current_season.net)}}</b></span></div></section>
    <div v-if="economy.sale_pressure?.status==='active'" class="financial-guidance"><strong>Consecuencia deportiva: venta exigida</strong><p>El consejo necesita {{formatMoney(economy.sale_pressure.remaining)}} antes del {{economy.sale_pressure.deadline}}. Una venta real reduce esa exigencia.</p></div>
  </article>
  <aside class="side-stack">
    <article class="football-panel"><h2>Fichas más altas</h2><div class="salary-list"><button v-for="row in economy.top_salaries" :key="row.player_id" type="button" class="salary-row salary-button" @click="emit('open-player',{id:row.player_id,name:row.name})"><span><strong>{{row.name}}</strong><small>hasta {{row.end_year}}</small></span><b>{{formatMoney(row.salary)}}</b></button><p v-if="!economy.top_salaries?.length" class="rail-empty">Sin datos salariales.</p></div></article>
    <article class="football-panel"><h2>Últimos movimientos</h2><div class="ledger-list"><p v-for="(row,index) in (economy.recent_ledger||[]).slice(-10).reverse()" :key="`${row.date}-${index}`" class="ledger-row"><span><small>{{row.date}}</small>{{row.kind}}</span><b :class="Number(row.amount)>=0?'good-text':'bad-cell'">{{Number(row.amount)>=0?'+':''}}{{formatMoney(row.amount)}}</b></p><p v-if="!economy.recent_ledger?.length" class="rail-empty">Todavía no hay movimientos registrados.</p></div></article>
    <article v-if="economy.longitudinal?.history?.length" class="football-panel"><h2>Temporadas</h2><div class="ledger-list"><p v-for="row in [...economy.longitudinal.history].reverse().slice(0,6)" :key="row.season" class="ledger-row"><span><strong>{{row.season}}</strong><small>flujo acumulado</small></span><b :class="Number(row.net)>=0?'good-text':'bad-cell'">{{formatMoney(row.net)}}</b></p></div></article>
    <article v-if="economy.contract_data_note" class="football-panel context-card"><h2>Origen de datos</h2><p>{{economy.contract_data_note}}</p></article>
  </aside>
</section>
</template>