from __future__ import annotations

from pathlib import Path
import json
import sys
from collections import Counter
from typing import Any
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'backend'))
from tools.deepen_historical_profiles_and_metadata_v031 import ROLE_TO_BROAD, ROLE_TO_LABEL, comparable, profile_gap_stats, role_ratings  # noqa: E402
from tools.review_created_player_profiles import materialise_attributes  # noqa: E402

DATA = ROOT / 'data' / 'football9394'
SNAP = DATA / 'historical_snapshot.json'
REG = DATA / 'created_players_registry.json'
QUEUE = DATA / 'bdfutbol_photo_queue.json'
STAGE = DATA / 'turkey_1993_94_roster_staging.json'
PHOTO_DIR = ROOT / 'frontend' / 'public' / 'historical9394' / 'players'
RAW_PHOTO_DIR = ROOT / '.tmp_photos_v035'

BDF_ZEYTIN = 'https://www.bdfutbol.com/en/t/t1993-949025.html'
BDF_KARABUK = 'https://www.bdfutbol.com/en/t/t1993-9410744.html'
BDF_KARSIYAKA = 'https://www.bdfutbol.com/en/t/t1993-949026.html?t=seg'
BDF_SARIYER = 'https://www.bdfutbol.com/en/t/t1993-949024.html'

COUNTRY_NAME = {
    4:'Alemania',8:'Albania',14:'Argelia',20:'Bosnia-Herzegovina',21:'Bulgaria',36:'Eslovaquia',37:'Eslovenia',
    40:'Rusia',43:'Escocia',54:'Macedonia',70:'Polonia',75:'República Federal de Yugoslavia',78:'Sudáfrica',
    84:'Turquía',85:'Ucrania',112:'Zambia',132:'Kazajistán',202:'Tayikistán',206:'Turkmenistán',
}

# Broad-only records deliberately do not claim a specialist role. Their internal role is a neutral carrier for the
# sourced line of play (3 defender, 7 midfielder, 17 forward). Exact roles are used only where corroborated.
P: dict[int, dict[str, Any]] = {9496541: {'club': 'Zeytinburnuspor',
           'name': 'Miralem Ibrahimović',
           'dob': '1963-01-18',
           'nat': [20],
           'birth_country': None,
           'place': 'Banovići (Yugoslavia)',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '44118',
           'height': 193,
           'note': 'BDFutbol labels the modern birth country Bosnia-Herzegovina; 1963 birthplace is retained historically as Yugoslavia without retrofitting a '
                   'successor-state birth_country_id.'},
 9496542: {'club': 'Zeytinburnuspor',
           'name': 'Kadri Sancak',
           'dob': '1966-09-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Treibine',
           'role': 3,
           'pos': 'Defender',
           'bdf': '700592',
           'precision': 'broad_only',
           'note': 'BDFutbol records place of birth as Treibine and birth country Turkey; the source spelling/context is retained rather than silently '
                   'reinterpreted.'},
 9496543: {'club': 'Zeytinburnuspor',
           'name': 'Yusuf Uzuner',
           'dob': '1962-09-23',
           'nat': [84],
           'birth_country': 84,
           'place': 'Kocaeli',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179951',
           'precision': 'broad_only'},
 9496544: {'club': 'Zeytinburnuspor',
           'name': 'Ali Aydoğan',
           'dob': '1963-08-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Ordu',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1176411',
           'precision': 'broad_only'},
 9496545: {'club': 'Zeytinburnuspor',
           'name': 'Taner Alpak',
           'dob': '1967-11-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 3,
           'pos': 'Defender',
           'bdf': '702825',
           'precision': 'broad_only'},
 9496546: {'club': 'Zeytinburnuspor',
           'name': 'Erol Gündoğdu',
           'dob': '1965-10-02',
           'nat': [84],
           'birth_country': 84,
           'place': 'Gümüşhane',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '702572',
           'precision': 'broad_only'},
 9496547: {'club': 'Zeytinburnuspor',
           'name': 'Ján Gabriel',
           'dob': '1962-04-18',
           'nat': [36],
           'birth_country': 36,
           'place': 'Trnava',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179949',
           'precision': 'broad_only'},
 9496548: {'club': 'Zeytinburnuspor',
           'name': 'Ahmet Kanca',
           'dob': '1963-05-16',
           'nat': [84],
           'birth_country': 84,
           'place': 'Sürmene (Trabzon)',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1178710',
           'precision': 'broad_only'},
 9496549: {'club': 'Zeytinburnuspor',
           'name': 'Kemal Yıldırım',
           'dob': '1958-05-15',
           'nat': [84],
           'birth_country': 84,
           'place': 'Ordu',
           'role': 17,
           'pos': 'Forward',
           'bdf': '702886',
           'precision': 'broad_only'},
 9496550: {'club': 'Zeytinburnuspor',
           'name': 'Uğur Kiremitçi',
           'dob': '1966-03-31',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1175511',
           'precision': 'broad_only'},
 9496551: {'club': 'Zeytinburnuspor',
           'name': 'Adnan Baytar',
           'dob': '1964-01-21',
           'nat': [84],
           'birth_country': 84,
           'place': 'Trabzon',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1175488',
           'precision': 'broad_only'},
 9496552: {'club': 'Zeytinburnuspor',
           'name': 'Süleyman Kocakara',
           'dob': '1958-11-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1179950'},
 9496553: {'club': 'Zeytinburnuspor',
           'name': 'Serkan Reçber',
           'dob': '1975-10-18',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bakırköy (Istanbul)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '55595',
           'precision': 'broad_only'},
 9496554: {'club': 'Zeytinburnuspor',
           'name': 'Soner Ayçiçek',
           'dob': '1966-07-04',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1178709',
           'precision': 'broad_only'},
 9496555: {'club': 'Zeytinburnuspor',
           'name': 'Gürses Kılıç',
           'dob': '1967-03-25',
           'nat': [84],
           'birth_country': 84,
           'place': 'Konya',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1175498',
           'precision': 'broad_only'},
 9496556: {'club': 'Zeytinburnuspor',
           'name': 'Matjaž Cvikl',
           'dob': '1967-01-13',
           'nat': [37],
           'birth_country': None,
           'place': 'Slovenj Gradec (Yugoslavia)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1175508',
           'precision': 'broad_only',
           'note': 'Born in SFR Yugoslavia; Slovenian football identity is retained while the historical birth state is stored textually.'},
 9496557: {'club': 'Zeytinburnuspor',
           'name': 'Yılmaz Ece',
           'dob': None,
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1178713',
           'birth_year': 1964,
           'note': 'BDFutbol supplies only birth year 1964; month/day are deliberately not invented.'},
 9496558: {'club': 'Zeytinburnuspor',
           'name': 'Fikret Durak',
           'dob': '1972-11-22',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1175509',
           'precision': 'broad_only'},
 9497319: {'club': 'Zeytinburnuspor',
           'name': 'Yasin Avcıoğlu',
           'dob': '1971-10-11',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1175328',
           'precision': 'broad_only'},
 9497320: {'club': 'Zeytinburnuspor',
           'name': 'Metin Tokoğlu',
           'dob': '1966-03-20',
           'nat': [84],
           'birth_country': 84,
           'place': 'Muş',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1178715',
           'precision': 'broad_only'},
 9497321: {'club': 'Zeytinburnuspor',
           'name': 'Gürsel Hattat',
           'dob': '1965-10-06',
           'nat': [84],
           'birth_country': 84,
           'place': 'Kırcaali',
           'role': 17,
           'pos': 'Forward',
           'bdf': '702937',
           'precision': 'broad_only',
           'note': 'BDFutbol records Kırcaali with Turkey as birth country; no unsourced correction is applied.'},
 9497322: {'club': 'Zeytinburnuspor',
           'name': 'Kadir Sünnetçiler',
           'dob': '1964-03-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Edirne',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1178714',
           'precision': 'broad_only'},
 9497323: {'club': 'Zeytinburnuspor',
           'name': 'Metin Aydemir',
           'dob': '1969-06-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bursa',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1178720',
           'precision': 'broad_only'},
 9497324: {'club': 'Zeytinburnuspor',
           'name': 'Uğur Eren',
           'dob': '1966-01-10',
           'nat': [84],
           'birth_country': 84,
           'place': 'Gaziantep',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179952',
           'precision': 'broad_only'},
 9497325: {'club': 'Zeytinburnuspor',
           'name': 'Mehmet Ünver',
           'dob': '1967-04-07',
           'nat': [84],
           'birth_country': 84,
           'place': 'Mersin',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179953',
           'precision': 'broad_only'},
 9497326: {'club': 'Zeytinburnuspor',
           'name': 'İbrahim Köseoğlu',
           'dob': '1968-01-16',
           'nat': [84],
           'birth_country': 21,
           'place': None,
           'role': 3,
           'pos': 'Defender',
           'bdf': '702734',
           'precision': 'broad_only',
           'note': 'Turkish footballer born in Bulgaria; Turkish sporting nationality and Bulgarian birthplace are stored separately.'},
 9496559: {'club': 'Karabükspor',
           'name': 'Fevzi Layiç',
           'dob': '1970-11-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '55591'},
 9496560: {'club': 'Karabükspor',
           'name': 'Şakir Özkayımoğlu',
           'dob': '1964-05-12',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1178360',
           'precision': 'broad_only'},
 9496561: {'club': 'Karabükspor',
           'name': 'Hakan Ünsal',
           'dob': '1973-05-14',
           'nat': [84],
           'birth_country': 84,
           'place': 'Sinop',
           'role': 2,
           'pos': 'Left Back',
           'bdf': '94265',
           'height': 178,
           'weight': 83,
           'position_url': 'https://www.bdfutbol.com/en/j/j94265.html',
           'note': 'BDFutbol explicitly gives Left back, so this profile is specialist rather than broad-only.'},
 9496562: {'club': 'Karabükspor',
           'name': 'Levent Açıkgöz',
           'dob': '1971-01-04',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1101075',
           'precision': 'broad_only'},
 9496563: {'club': 'Karabükspor',
           'name': 'İlhan Özer',
           'dob': '1966-11-25',
           'nat': [84],
           'birth_country': 84,
           'place': 'Karabük',
           'role': 3,
           'pos': 'Defender',
           'bdf': '702569',
           'precision': 'broad_only'},
 9496564: {'club': 'Karabükspor',
           'name': 'Tarık Yurttaş',
           'dob': '1967-02-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Diyarbakır',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '702823',
           'precision': 'broad_only'},
 9496565: {'club': 'Karabükspor',
           'name': 'Sedat Kalaycı',
           'dob': '1966-07-05',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1172029',
           'precision': 'broad_only',
           'height': 179},
 9496566: {'club': 'Karabükspor',
           'name': 'Hüseyin Çoban',
           'dob': '1966-01-02',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bayburt',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1173817',
           'precision': 'broad_only'},
 9496567: {'club': 'Karabükspor',
           'name': 'Uğur Dağdelen',
           'dob': '1973-10-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Amasya',
           'role': 17,
           'pos': 'Forward',
           'bdf': '700577',
           'precision': 'broad_only'},
 9496568: {'club': 'Karabükspor',
           'name': 'Ümit İnal',
           'dob': '1969-07-18',
           'nat': [84],
           'birth_country': 84,
           'place': 'Şanlıurfa',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1136862',
           'precision': 'broad_only',
           'height': 190},
 9496569: {'club': 'Karabükspor',
           'name': 'Hasan Şermet',
           'dob': '1969-07-14',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1169816',
           'precision': 'broad_only'},
 9496570: {'club': 'Karabükspor',
           'name': 'Ibrahim Hasançebi',
           'dob': '1970-09-15',
           'nat': [84],
           'birth_country': 84,
           'place': 'Trabzon',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '707940'},
 9496571: {'club': 'Karabükspor',
           'name': 'Benyencef Haraoui',
           'dob': '1965-05-12',
           'nat': [14],
           'birth_country': 14,
           'place': 'Argel',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '88624',
           'precision': 'broad_only',
           'height': 176,
           'weight': 75},
 9496572: {'club': 'Karabükspor',
           'name': 'Nejat Özyıldırım',
           'dob': '1969-05-24',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179624',
           'precision': 'broad_only'},
 9496573: {'club': 'Karabükspor',
           'name': 'Ali Çebi',
           'dob': '1968-08-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Trabzon',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179619',
           'precision': 'broad_only'},
 9496574: {'club': 'Karabükspor',
           'name': 'Fikret Bademci',
           'dob': '1972-01-12',
           'nat': [84],
           'birth_country': 84,
           'place': 'Konya',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179620',
           'precision': 'broad_only'},
 9496575: {'club': 'Karabükspor',
           'name': 'Kıvanç Bozkurt',
           'dob': '1964-02-28',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1179622'},
 9496576: {'club': 'Karabükspor',
           'name': 'Önder Cankat',
           'dob': '1973-11-20',
           'nat': [84],
           'birth_country': 84,
           'place': 'Ankara',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1178572',
           'precision': 'broad_only'},
 9497327: {'club': 'Karabükspor',
           'name': 'Candan Sayın',
           'dob': '1970-08-09',
           'nat': [84],
           'birth_country': 84,
           'place': 'Rize',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1171757',
           'precision': 'broad_only'},
 9497328: {'club': 'Karabükspor',
           'name': 'Innocent Linda Buthelezi',
           'dob': '1969-06-28',
           'nat': [78],
           'birth_country': 78,
           'place': 'Johannesburg',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179818',
           'precision': 'broad_only',
           'height': 180},
 9497329: {'club': 'Karabükspor',
           'name': 'Ercan Kalkan',
           'dob': '1966-10-11',
           'nat': [84],
           'birth_country': 84,
           'place': 'Yozgat',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179623',
           'precision': 'broad_only'},
 9497330: {'club': 'Karabükspor',
           'name': 'Christopher Mwakapuki',
           'dob': '1967-06-10',
           'nat': [112],
           'birth_country': 112,
           'place': 'Ndola',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179822',
           'precision': 'broad_only'},
 9497331: {'club': 'Karabükspor',
           'name': 'Özcan İlarslan',
           'dob': '1964-06-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Trabzon',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179621',
           'precision': 'broad_only'},
 9497332: {'club': 'Karabükspor',
           'name': 'Burhan Baygın',
           'dob': '1967-06-28',
           'nat': [84],
           'birth_country': 84,
           'place': 'Samandağ (Hatay)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179625',
           'precision': 'broad_only'},
 9497333: {'club': 'Karabükspor',
           'name': 'Kerim Tasçı',
           'dob': '1971-02-07',
           'nat': [84],
           'birth_country': 84,
           'place': 'Karabük',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179812',
           'precision': 'broad_only'},
 9497334: {'club': 'Karabükspor',
           'name': 'Tolga Sarı',
           'dob': '1971-12-02',
           'nat': [84],
           'birth_country': 84,
           'place': 'Zonguldak',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179815',
           'precision': 'broad_only'},
 9497335: {'club': 'Karabükspor',
           'name': 'Hüseyin Saraç',
           'dob': '1970-09-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bayburt',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179813',
           'precision': 'broad_only'},
 9496577: {'club': 'Karşıyaka',
           'name': 'Ilia Valov Ivanov',
           'dob': '1961-12-29',
           'nat': [21],
           'birth_country': 21,
           'place': 'Knezha',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '705929',
           'height': 188},
 9496578: {'club': 'Karşıyaka',
           'name': 'Şenol Yavaş',
           'dob': '1973-06-22',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 3,
           'pos': 'Defender',
           'bdf': '56368',
           'precision': 'broad_only'},
 9496579: {'club': 'Karşıyaka',
           'name': 'Saffet Akbaş',
           'dob': '1968-09-08',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 3,
           'pos': 'Defender',
           'bdf': '55572',
           'precision': 'broad_only'},
 9496580: {'club': 'Karşıyaka',
           'name': 'Bayram Mercan',
           'dob': '1964-04-23',
           'nat': [84],
           'birth_country': 84,
           'place': 'Edirne',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179829',
           'precision': 'broad_only'},
 9496581: {'club': 'Karşıyaka',
           'name': 'Murat Sır',
           'dob': '1974-12-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1176281',
           'precision': 'broad_only'},
 9496582: {'club': 'Karşıyaka',
           'name': 'Atilla Güneş',
           'dob': '1974-07-13',
           'nat': [84, 4],
           'birth_country': 4,
           'place': 'Heilbronn',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '55587',
           'precision': 'broad_only'},
 9496583: {'club': 'Karşıyaka',
           'name': 'Yüksel Kepoğlu',
           'dob': '1968-07-04',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '57067',
           'precision': 'broad_only'},
 9496584: {'club': 'Karşıyaka',
           'name': 'Hakan Çıkrıkçıoğlu',
           'dob': '1968-08-14',
           'nat': [84],
           'birth_country': 84,
           'place': 'Tokat',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179831',
           'precision': 'broad_only'},
 9496585: {'club': 'Karşıyaka',
           'name': 'Ziya Yıldız',
           'dob': '1960-09-21',
           'nat': [20, 84],
           'birth_country': None,
           'place': 'Sarajevo (Yugoslavia)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '702879',
           'precision': 'broad_only',
           'note': 'Also known as Zijad Švrakić. Bosnia-Herzegovina and acquired Turkish nationality are retained; 1960 birthplace is stored as Yugoslavia '
                   'rather than retrofitted.'},
 9496586: {'club': 'Karşıyaka',
           'name': 'Recep Umut',
           'dob': '1967-12-20',
           'nat': [84],
           'birth_country': 84,
           'place': 'Manisa',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1173844',
           'precision': 'broad_only'},
 9496587: {'club': 'Karşıyaka',
           'name': 'Erhan Kiremitçi',
           'dob': '1963-01-17',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179837',
           'precision': 'broad_only'},
 9496588: {'club': 'Karşıyaka',
           'name': 'Atilla Küçüktaka',
           'dob': '1972-03-26',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1127314'},
 9496589: {'club': 'Karşıyaka',
           'name': 'Taygun Erdem',
           'dob': '1967-10-02',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bursa',
           'role': 3,
           'pos': 'Defender',
           'bdf': '45601',
           'precision': 'broad_only'},
 9496590: {'club': 'Karşıyaka',
           'name': 'Serdar Kahraman',
           'dob': '1973-09-16',
           'nat': [84],
           'birth_country': 84,
           'place': 'Diyarbakır',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179838',
           'precision': 'broad_only'},
 9496591: {'club': 'Karşıyaka',
           'name': 'Dragi Kanatlarovski',
           'dob': '1960-11-01',
           'nat': [54],
           'birth_country': None,
           'place': 'Bitola (Yugoslavia)',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '622',
           'precision': 'broad_only',
           'height': 185,
           'weight': 83,
           'note': 'BDFutbol uses the modern North Macedonia birth-country label; 1960 birthplace is retained as Yugoslavia.'},
 9496592: {'club': 'Karşıyaka',
           'name': 'Bilal Şar',
           'dob': '1968-01-15',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '45604',
           'precision': 'broad_only'},
 9496593: {'club': 'Karşıyaka',
           'name': 'Nejat Topal',
           'dob': '1960-11-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bornova (Izmir)',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1179841'},
 9496594: {'club': 'Karşıyaka',
           'name': 'Mustafa Fedai',
           'dob': '1968-05-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bornova',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1136760',
           'precision': 'broad_only'},
 9497336: {'club': 'Karşıyaka',
           'name': 'Jacek Cyzio',
           'dob': '1968-09-06',
           'nat': [70],
           'birth_country': 70,
           'place': 'Chrzanów',
           'role': 17,
           'pos': 'Forward',
           'bdf': '702770',
           'precision': 'broad_only'},
 9497337: {'club': 'Karşıyaka',
           'name': 'Mirza Golubica',
           'dob': '1965-05-18',
           'nat': [20, 75],
           'birth_country': None,
           'place': 'Zenica (Yugoslavia)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '9263',
           'precision': 'broad_only',
           'height': 188,
           'weight': 82,
           'note': 'BDFutbol records Bosnia-Herzegovina and Serbia nationalities. The project maps the legacy Serbia id to the 1993 FR Yugoslavia state; '
                   'birthplace remains historical Yugoslavia.'},
 9497338: {'club': 'Karşıyaka',
           'name': 'Bahadır Tamsan',
           'dob': '1974-09-21',
           'nat': [84],
           'birth_country': 84,
           'place': None,
           'role': 3,
           'pos': 'Defender',
           'bdf': '1176284',
           'precision': 'broad_only'},
 9497339: {'club': 'Karşıyaka',
           'name': 'Yaşar Akçura',
           'dob': '1969-10-02',
           'nat': [84],
           'birth_country': 84,
           'place': 'Diyarbakır',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179836',
           'precision': 'broad_only'},
 9497340: {'club': 'Karşıyaka',
           'name': 'Cenk Gürgenç',
           'dob': '1975-02-18',
           'nat': [84, 4],
           'birth_country': 4,
           'place': 'Hannover',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1176285',
           'precision': 'broad_only'},
 9497341: {'club': 'Karşıyaka',
           'name': 'Ahmet Bora Orman Kocaman',
           'dob': '1972-06-22',
           'nat': [84],
           'birth_country': 84,
           'place': 'Ankara',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179839',
           'precision': 'broad_only'},
 9497342: {'club': 'Karşıyaka',
           'name': 'Talat Alptekin',
           'dob': '1971-10-05',
           'nat': [84],
           'birth_country': 84,
           'place': 'Hanak (Ardahan)',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179840',
           'precision': 'broad_only'},
 9496595: {'club': 'Sarıyer',
           'name': 'Metin Mert',
           'dob': '1965-05-21',
           'nat': [84, 4],
           'birth_country': 4,
           'place': 'Duisburg',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '701150',
           'note': 'BDFutbol profile name is Metin Mert and legal complete name Detlef Müller; the football name is used as display identity and '
                   'Turkish/German nationality is retained.'},
 9496596: {'club': 'Sarıyer',
           'name': 'Feridun Cemal Alkan',
           'dob': '1964-11-13',
           'nat': [84],
           'birth_country': 84,
           'place': 'Rize',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179940',
           'precision': 'broad_only'},
 9496597: {'club': 'Sarıyer',
           'name': 'Evgeny Viktorovich Yarovenko',
           'dob': '1962-08-17',
           'nat': [85, 132],
           'birth_country': None,
           'place': 'Karatau (USSR)',
           'role': 3,
           'pos': 'Centre-Back',
           'bdf': '1040412',
           'height': 185,
           'position_url': 'https://www.transfermarkt.com/evgeniy-yarovenko/profil/spieler/214383',
           'note': 'BDFutbol and Transfermarkt give 17/08/1962; some secondary sources give 1963. Transfermarkt identifies Centre-Back and Ukraine/Kazakhstan '
                   'citizenship. Former-USSR birthplace is retained textually.'},
 9496598: {'club': 'Sarıyer',
           'name': 'Ali Ravcı',
           'dob': '1973-01-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Malatya',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1100565',
           'precision': 'broad_only',
           'height': 188,
           'weight': 78},
 9496599: {'club': 'Sarıyer',
           'name': 'Esat Bayram',
           'dob': '1964-09-14',
           'nat': [84],
           'birth_country': 84,
           'place': 'Kırklareli',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '702935',
           'precision': 'broad_only'},
 9496600: {'club': 'Sarıyer',
           'name': 'Beyhan Çalışkan',
           'dob': '1960-04-06',
           'nat': [84, 21],
           'birth_country': 21,
           'place': 'Ruse',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '702938',
           'precision': 'broad_only'},
 9496601: {'club': 'Sarıyer',
           'name': 'Selçuk Bıyıklı',
           'dob': '1966-10-01',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179946',
           'precision': 'broad_only'},
 9496602: {'club': 'Sarıyer',
           'name': 'Mehmet Kaplan',
           'dob': '1972-01-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Elazığ',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1170016',
           'precision': 'broad_only'},
 9496603: {'club': 'Sarıyer',
           'name': 'Nusret Erdi Demir',
           'dob': '1964-11-15',
           'nat': [84],
           'birth_country': 84,
           'place': 'Izmir',
           'role': 17,
           'pos': 'Forward',
           'bdf': '45600',
           'precision': 'broad_only'},
 9496604: {'club': 'Sarıyer',
           'name': 'Sercan Görgülü',
           'dob': '1960-12-05',
           'nat': [84],
           'birth_country': 84,
           'place': 'Hızırşah (Muğla)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179943',
           'precision': 'broad_only',
           'height': 173},
 9496605: {'club': 'Sarıyer',
           'name': 'Osman Cengiz Güzeltepe',
           'dob': '1964-01-27',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1175391',
           'precision': 'broad_only'},
 9496606: {'club': 'Sarıyer',
           'name': 'Tufan Engin',
           'dob': '1966-11-25',
           'nat': [84],
           'birth_country': 84,
           'place': 'Tekirdağ',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1175418'},
 9496607: {'club': 'Sarıyer',
           'name': 'Birol Demirhan',
           'dob': '1970-08-25',
           'nat': [84],
           'birth_country': 84,
           'place': 'Gümüşhane',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1141650',
           'precision': 'broad_only',
           'height': 178},
 9496608: {'club': 'Sarıyer',
           'name': 'Nermin Vazda',
           'dob': '1967-08-30',
           'nat': [20],
           'birth_country': None,
           'place': 'Višegrad (Yugoslavia)',
           'role': 17,
           'pos': 'Forward',
           'bdf': '1179948',
           'precision': 'broad_only',
           'note': 'BDFutbol uses modern Bosnia-Herzegovina for the birthplace; 1967 historical state is retained as Yugoslavia.'},
 9496609: {'club': 'Sarıyer',
           'name': 'Osman Yıldırım',
           'dob': '1965-07-12',
           'nat': [84],
           'birth_country': 84,
           'place': 'Tonya (Trabzon)',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179941',
           'precision': 'broad_only'},
 9496610: {'club': 'Sarıyer',
           'name': 'Sinan Engin',
           'dob': '1964-11-04',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 17,
           'pos': 'Forward',
           'bdf': '42714',
           'precision': 'broad_only',
           'note': 'BDFutbol typography displays Sìnan Engin; normalized football name Sinan Engin is used.'},
 9496611: {'club': 'Sarıyer',
           'name': 'Seyhan Cenk Tekelioğlu',
           'dob': '1973-08-04',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 0,
           'pos': 'Goalkeeper',
           'bdf': '1120556',
           'height': 185},
 9496612: {'club': 'Sarıyer',
           'name': 'Hakan Çimen',
           'dob': '1973-09-08',
           'nat': [84],
           'birth_country': 84,
           'place': 'Ankara',
           'role': 3,
           'pos': 'Defender',
           'bdf': '56029',
           'precision': 'broad_only'},
 9497343: {'club': 'Sarıyer',
           'name': 'Sami Başar',
           'dob': '1970-05-03',
           'nat': [84],
           'birth_country': 84,
           'place': 'Malatya',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179944',
           'precision': 'broad_only'},
 9497344: {'club': 'Sarıyer',
           'name': 'Ramazan Baybatmaz',
           'dob': '1969-05-25',
           'nat': [84],
           'birth_country': 84,
           'place': 'Adıyaman',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179942',
           'precision': 'broad_only'},
 9497345: {'club': 'Sarıyer',
           'name': 'Salihi Heroll',
           'dob': '1964-12-06',
           'nat': [8],
           'birth_country': None,
           'place': None,
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1178660',
           'precision': 'broad_only',
           'note': 'BDFutbol assigns a modern Bosnia-Herzegovina birth-country label without a place; independent player profiles identify Albanian '
                   'nationality and Yugoslav birth. No successor-state birthplace is fabricated.'},
 9497346: {'club': 'Sarıyer',
           'name': 'Erdinç Aktaş',
           'dob': '1970-07-13',
           'nat': [84],
           'birth_country': 84,
           'place': 'Istanbul',
           'role': 3,
           'pos': 'Defender',
           'bdf': '1179947',
           'precision': 'broad_only'},
 9497347: {'club': 'Sarıyer',
           'name': 'Şenol Ulusavaş',
           'dob': '1962-11-10',
           'nat': [84],
           'birth_country': 84,
           'place': 'Eskişehir',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '55609',
           'precision': 'broad_only'},
 9497348: {'club': 'Sarıyer',
           'name': 'Engin Ülker',
           'dob': '1961-12-10',
           'nat': [84],
           'birth_country': 84,
           'place': 'Bartın',
           'role': 7,
           'pos': 'Midfielder',
           'bdf': '1179945',
           'precision': 'broad_only'}}

# Filled after downloading verified BDF portraits. Key -> original portrait URL.
PHOTO_URLS: dict[int,str] = {9496541: 'https://www.bdfutbol.com/en/i/j/44118.jpg?v=1659700905',
 9496547: 'https://www.bdfutbol.com/en/i/j/1179949.jpg?v=1782600126',
 9496553: 'https://www.bdfutbol.com/en/i/j/55595.jpg?v=1772710773',
 9496559: 'https://www.bdfutbol.com/en/i/j/55591.jpg?v=1782459134',
 9496561: 'https://www.bdfutbol.com/en/i/j/94265.jpg?v=1393712916',
 9496571: 'https://www.bdfutbol.com/en/i/j/88624.jpg?v=1780320302',
 9497328: 'https://www.bdfutbol.com/en/i/j/1179818.jpg?v=1783001502',
 9496590: 'https://www.bdfutbol.com/en/i/j/1179838.jpg?v=1782511782',
 9496591: 'https://www.bdfutbol.com/en/i/j/622.jpg?v=1303494774',
 9496592: 'https://www.bdfutbol.com/en/i/j/45604.jpg?v=1660746472',
 9496593: 'https://www.bdfutbol.com/en/i/j/1179841.jpg?v=1782512173',
 9496594: 'https://www.bdfutbol.com/en/i/j/1136760.jpg?v=1783001675',
 9497336: 'https://www.bdfutbol.com/en/i/j/702770.jpg?v=1706693814',
 9497337: 'https://www.bdfutbol.com/en/i/j/9263b.jpg?v=1245689820',
 9497339: 'https://www.bdfutbol.com/en/i/j/1179836.jpg?v=1782510827',
 9496595: 'https://www.bdfutbol.com/i/j/701150.jpg?v=1738510703',
 9496597: 'https://www.bdfutbol.com/i/j/1040412.jpg?v=1768308545',
 9496600: 'https://www.bdfutbol.com/i/j/702938.jpg?v=1708332959',
 9496608: 'https://www.bdfutbol.com/i/j/1179948.jpg?v=1782599809',
 9496610: 'https://www.bdfutbol.com/i/j/42714.jpg?v=1649326532'}

ROLE_ES={0:'Portero',1:'Lateral derecho',2:'Lateral izquierdo',3:'Defensa central',4:'Defensa central',5:'Líbero',6:'Mediocentro defensivo',7:'Centrocampista',8:'Mediapunta',9:'Interior derecho',10:'Interior derecho',11:'Extremo derecho',12:'Extremo derecho',13:'Interior izquierdo',14:'Interior izquierdo',15:'Extremo izquierdo',16:'Extremo izquierdo',17:'Delantero centro'}

def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def dump(p,o): Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def split_name(n):
    a=n.split(); return (None,n) if len(a)==1 else (' '.join(a[:-1]),a[-1])

def reattribute(player,new_role,originals,sid):
    a,b=comparable(originals,ROLE_TO_BROAD[new_role],int(player.get('overall') or 70),sid)
    player['attributes']=materialise_attributes(int(player.get('overall') or 70),a,b)
    player['attribute_source']='fixed_source_comparable_role_correction_0.35'
    player['attribute_comparable_source_ids']=[int(a['source_id']),int(b['source_id'])]

def apply_profile(player,patch,originals,sid):
    old={'display_name':player.get('display_name'),'role':int(player.get('primary_role') or 0),'broad':player.get('broad_position'),'position':player.get('historical_position_1993_94'),'birth_date':player.get('birth_date'),'international_country_id':player.get('international_country_id')}
    first,surname=split_name(patch['name']); player['display_name']=patch['name']; player['first_name']=first; player['surname1']=surname
    if patch.get('dob'):
        player['birth_date']=patch['dob']+'T00:00:00'; player.pop('historical_birth_year_only',None)
    else:
        # keep a genuine gap rather than creating 01/01 from a year-only source
        player['birth_date']=None; player['historical_birth_year_only']=int(patch['birth_year'])
    if patch.get('birth_country') is not None: player['birth_country_id']=int(patch['birth_country'])
    else: player.pop('birth_country_id',None)
    player['international_country_id']=int(patch['nat'][0]); player['profile_nationality_country_ids']=[int(x) for x in patch['nat']]
    if len(patch['nat'])>1: player['secondary_nationality_country_id']=int(patch['nat'][1])
    else: player.pop('secondary_nationality_country_id',None)
    player['historical_birth_place_text']=patch.get('place')
    profile_url=f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html"
    player['historical_birth_place_source_url']=profile_url; player['historical_birth_place_source_label']='BDFutbol individual profile v0.35'
    player['bdfutbol_id']=str(patch['bdf']); player['bdfutbol_url']=profile_url
    if patch.get('height') is not None: player['height_cm']=int(patch['height'])
    if patch.get('weight') is not None: player['weight_kg']=int(patch['weight'])
    role=int(patch['role']); old_role=int(player.get('primary_role') or 0); old_broad=player.get('broad_position')
    player['primary_role']=role; player['broad_position']=ROLE_TO_BROAD[role]; player['role_ratings']=role_ratings(role)
    precision=patch.get('precision','exact'); player['profile_position_precision']=precision; player['source_profile_position']=patch['pos']; player['profile_review_required']=precision=='broad_only'
    if precision=='broad_only':
        player['historical_position_1993_94']=patch['pos']+' (exact role unresolved)'; player['historical_position_source']='BDFutbol individual profile — broad position only v0.35'
    else:
        player['historical_position_1993_94']=ROLE_TO_LABEL[role]; player['historical_position_source']='BDFutbol + specialist cross-check v0.35'
    player['historical_position_source_url']=patch.get('position_url') or profile_url
    player['historical_profile_source']='BDFutbol individual profile + specialist cross-check v0.35'; player['historical_profile_source_url']=profile_url
    if patch.get('note'): player['historical_profile_source_note']=patch['note']
    if role!=old_role or player['broad_position']!=old_broad: reattribute(player,role,originals,sid)
    return {'source_id':sid,'club':patch['club'],'before':old,'after':{'display_name':player['display_name'],'role':player['primary_role'],'broad':player['broad_position'],'position':player['historical_position_1993_94'],'birth_date':player.get('birth_date'),'international_country_id':player['international_country_id']},'role_changed':role!=old_role,'precision':precision}

def sync(target,player,patch):
    target.update({'display_name':player['display_name'],'first_name':player.get('first_name'),'surname1':player.get('surname1'),'birth_date':str(player['birth_date'])[:10] if player.get('birth_date') else None,'country_id':player.get('international_country_id'),'country_name':COUNTRY_NAME.get(player.get('international_country_id')),'broad_position':player.get('broad_position'),'historical_position_1993_94':player.get('historical_position_1993_94'),'profile_review_required':bool(player.get('profile_review_required')),'individual_profile_source':'BDFutbol/specialist profile cross-check v0.35','individual_profile_source_url':f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html",'historical_birth_place_text':patch.get('place'),'bdfutbol_id':str(patch['bdf']),'bdfutbol_url':f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html"})
    if patch.get('birth_year') and not patch.get('dob'): target['historical_birth_year_only']=int(patch['birth_year'])

def update_stage(stage,sid,player,patch):
    club=next(c for c in stage['clubs'] if c.get('name')==patch['club']); row=next(r for r in club['players'] if int(r.get('resolved_source_id') or -1)==sid)
    row.update({'resolved_display_name':player['display_name'],'resolved_primary_role':player['primary_role'],'resolved_exact_position':player['historical_position_1993_94'],'resolved_birth_date':player.get('birth_date'),'resolved_country_id':player['international_country_id'],'source_profile_position':patch['pos'],'profile_source':'BDFutbol/specialist profile cross-check v0.35','profile_source_url':f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html",'position_source':player['historical_position_source'],'position_source_url':player['historical_position_source_url'],'resolved_birth_place_text':patch.get('place'),'bdfutbol_id':str(patch['bdf']),'individual_profile_source_url':f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html"})
    if patch.get('birth_year') and not patch.get('dob'): row['resolved_birth_year_only']=int(patch['birth_year'])
    if patch.get('note'): row['profile_source_note']=patch['note']

def normalize_photos(by,reg_by,queue_by):
    PHOTO_DIR.mkdir(parents=True,exist_ok=True); rows=[]
    for sid,url in PHOTO_URLS.items():
        raw=RAW_PHOTO_DIR/f'{sid}.jpg'
        if not raw.exists(): continue
        try:
            with Image.open(raw) as im:
                rgb=im.convert('RGB'); fitted=ImageOps.fit(rgb,(40,55),method=Image.Resampling.LANCZOS,centering=(0.5,0.5)); out=PHOTO_DIR/f'{sid}.jpg'; fitted.save(out,'JPEG',quality=92,optimize=True)
            with Image.open(out) as ck:
                if ck.size!=(40,55) or ck.mode!='RGB' or ck.format!='JPEG': raise RuntimeError('bad normalized photo')
        except Exception:
            continue
        patch=P[sid]; profile_url=f"https://www.bdfutbol.com/en/j/j{patch['bdf']}.html"
        for target in (reg_by[sid],queue_by[sid]):
            target.update({'photo_filename':f'{sid}.jpg','photo_status':'bundled_normalized_bdfutbol','photo_width':40,'photo_height':55,'photo_format':'JPEG','photo_mode':'RGB','photo_source':'BDFutbol individual profile v0.35','photo_source_url':url,'bdfutbol_id':str(patch['bdf']),'bdfutbol_url':profile_url})
        rows.append({'source_id':sid,'display_name':by[sid]['display_name'],'photo_url':url,'asset':str((PHOTO_DIR/f'{sid}.jpg').relative_to(ROOT))})
    return rows

def fmt_num(value: int) -> str:
    return f'{value:,}'.replace(',', '.')

def biography(player,team,row):
    if player.get('profile_position_precision')=='broad_only':
        role={'POR':'Portero','DEF':'Defensa','MED':'Centrocampista','DEL':'Delantero'}.get(player.get('broad_position'),'Futbolista')
    else:
        role=ROLE_ES.get(int(player.get('primary_role') or 0),'Futbolista')
    parts=[f'{role} de {team} en la temporada 1993-94.']; stats=[]
    for key,label in [('appearances','partidos'),('starts','como titular')]:
        value=row.get(key)
        if isinstance(value,int) and value>=0: stats.append(f'{value} {label}')
    minutes=row.get('minutes')
    if isinstance(minutes,int) and minutes>=0: stats.append(f'{fmt_num(minutes)} minutos')
    if stats: parts.append('En el registro histórico figura con '+', '.join(stats)+'.')
    goals=row.get('goals')
    if int(player.get('primary_role') or 0)!=0 and isinstance(goals,int) and goals>=0:
        parts.append(f'Marcó {goals} gol'+('' if goals==1 else 'es')+'.')
    bd=player.get('birth_date')
    if bd:
        y,m,d=str(bd)[:10].split('-'); parts.append(f'Fecha de nacimiento registrada: {d}/{m}/{y}.')
    elif player.get('historical_birth_year_only'):
        parts.append(f"La fuente individual sólo documenta el año de nacimiento ({player['historical_birth_year_only']}); no se inventa día ni mes.")
    if player.get('historical_birth_place_text'):
        parts.append('Lugar de nacimiento documentado: '+str(player['historical_birth_place_text'])+'.')
    return ' '.join(parts)

def regenerate_bios(snap,stage):
    by={int(p['source_id']):p for p in snap['players']}; rows={}
    for c in stage['clubs']:
        for r in c['players']:
            sid=r.get('resolved_source_id')
            if sid is not None: rows.setdefault(int(sid),[]).append((c['name'],r))
    changed=0; missing=[]
    for sid in P:
        if sid not in rows:
            missing.append(sid); continue
        p=by[sid]; old=p.get('historical_biography_1993_94'); candidates=rows[sid]
        team_name=str(P[sid]['club']); chosen=candidates[0]
        for cand in candidates:
            if str(cand[0]).casefold()==team_name.casefold(): chosen=cand; break
        team,row=chosen; new=biography(p,team,row)
        p['historical_biography_1993_94']=new
        p.pop('historical_biography',None)
        p['historical_biography_source_url']=row.get('profile_source_url') or row.get('individual_profile_source_url') or f"https://www.bdfutbol.com/en/j/j{P[sid]['bdf']}.html"
        p['historical_biography_source_label']=row.get('profile_source') or 'BDFutbol/specialist profile cross-check v0.35'
        p['historical_biography_evidence']={'season':'1993-94','club':team,'appearances':row.get('appearances'),'starts':row.get('starts'),'minutes':row.get('minutes'),'goals':row.get('goals'),'staging_name':row.get('bdfutbol_name') or row.get('resolved_display_name')}
        p['historical_biography_status']='source_backed_season_summary'; p['historical_biography_staged_clubs']=[x[0] for x in candidates]
        changed+=old!=new
    if missing: raise RuntimeError(f'v0.35 curated players missing staging rows: {missing}')
    return {'profiles_considered':len(P),'biographies_changed':changed,'missing_stage_rows':0}

def main():
    snap=load(SNAP); reg=load(REG); queue=load(QUEUE); stage=load(STAGE)
    by={int(p['source_id']):p for p in snap['players']}; reg_by={int(p['source_id']):p for p in reg['players']}; queue_by={int(p['source_id']):p for p in queue['players']}
    originals=[p for p in snap['players'] if p.get('attributes') and not p.get('external_origin') and not p.get('creation_batch')]
    before=profile_gap_stats(snap); changes=[]
    missing=[sid for sid in P if sid not in by or sid not in reg_by or sid not in queue_by]
    if missing: raise RuntimeError(f'missing identities: {missing}')
    for sid,patch in P.items():
        p=by[sid]; changes.append(apply_profile(p,patch,originals,sid)); sync(reg_by[sid],p,patch); sync(queue_by[sid],p,patch); update_stage(stage,sid,p,patch)
    photos=normalize_photos(by,reg_by,queue_by); bios=regenerate_bios(snap,stage)
    dump(SNAP,snap); dump(REG,reg); dump(QUEUE,queue); dump(STAGE,stage)
    after=profile_gap_stats(snap)
    ids=[int(x['source_id']) for x in reg['players']]; qids=[int(x['source_id']) for x in queue['players']]
    if len(ids)!=len(set(ids)) or len(qids)!=len(set(qids)) or set(ids)!=set(qids): raise RuntimeError('identity registry integrity failure')
    audit={'schema_version':1,'checkpoint':'0.35.0-turkey-zeytinburnu-karabuk-karsiyaka-sariyer-deep','status':'pass','profile_gaps_before':before,'profile_gaps_after':after,'profiles':{'curated_this_batch':len(P),'by_club':dict(Counter(x['club'] for x in P.values())),'exact_specialist_roles':sum(x.get('precision','exact')=='exact' for x in P.values()),'broad_only_exact_role_unresolved':sum(x.get('precision')=='broad_only' for x in P.values()),'year_only_birth_records':sum(not x.get('dob') for x in P.values()),'role_corrections_this_batch':sum(bool(c['role_changed']) for c in changes),'changes':changes},'photos':{'new_normalized_bdfutbol_portraits':len(photos),'rows':photos,'total_bundled_normalized_bdfutbol':sum(r.get('photo_status')=='bundled_normalized_bdfutbol' for r in reg['players'])},'biographies':bios,'identity_integrity':{'registry_rows':len(ids),'unique_registry_ids':len(set(ids)),'sets_match':set(ids)==set(qids)},'source_policy':['No day/month is invented when the historical source only gives a birth year.','Broad positions are marked exact-role unresolved unless a specialist/federation source corroborates a role.','Former-USSR and former-Yugoslavia birthplaces are stored textually instead of retrofitting a modern successor-state birth_country_id.','Official federation data wins documented date conflicts; multi-source specialist corroboration wins a known BDFutbol date conflict.','No basketball 75/25 rule is used.']}
    dump(DATA/'historical_profiles_metadata_audit_v035.json',audit); dump(DATA/'historical_metadata_gaps_v035.json',{'checkpoint':audit['checkpoint'],'gaps':after}); dump(DATA/'historical_biographies_audit_v035.json',bios); dump(DATA/'bdfutbol_photo_normalization_v035_zeytin_karabuk_karsiyaka_sariyer.json',{'checkpoint':audit['checkpoint'],'status':'pass','portraits':photos})
    print(json.dumps({'curated':len(P),'exact_roles':audit['profiles']['exact_specialist_roles'],'broad_only':audit['profiles']['broad_only_exact_role_unresolved'],'year_only_births':audit['profiles']['year_only_birth_records'],'role_corrections':audit['profiles']['role_corrections_this_batch'],'photos_new':len(photos),'turkey_gaps_before':before['Turkey'],'turkey_gaps_after':after['Turkey']},ensure_ascii=False,indent=2))

if __name__=='__main__': main()
