from __future__ import annotations

"""Source-backed medical incidents for the persistent 1993-94 career.

The supplied MDB contains a detailed injury vocabulary (generic injury,
specific body zone and expected recovery ranges).  Those definitions are used
as structural source data.  They are *not* claims that a specific player had a
specific historical injury on a given date: match injuries are generated by the
career and carry explicit provenance.
"""

from datetime import date, timedelta
from functools import lru_cache
from random import Random
from typing import Any

from .source_catalog_runtime import default_source_catalog


@lru_cache(maxsize=1)
def _catalog_index() -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]], dict[int, dict[str, Any]], dict[int, dict[str, Any]]]:
    payload = default_source_catalog().payload.get("injuries") or {}
    generic = {int(row["Id"]): row for row in payload.get("generic", []) if row.get("Id") is not None}
    specific_zones = {int(row["Id"]): row for row in payload.get("specific_body_zones", []) if row.get("Id") is not None}
    body_zones = {int(row["Id"]): row for row in payload.get("body_zones", []) if row.get("Id") is not None}
    specific = [
        row for row in payload.get("specific", [])
        if row.get("ID") is not None and row.get("Lesion") is not None and row.get("Zona") is not None
        and float(row.get("Conv_max") or row.get("Conv_min") or 0) > 0
    ]
    return specific, generic, specific_zones, body_zones


def _label(generic_name: str, zone_name: str) -> str:
    generic_name = str(generic_name or "lesión").strip()
    zone_name = str(zone_name or "").strip()
    if not zone_name or zone_name.upper() == "GENERAL":
        return generic_name[:1].upper() + generic_name[1:]
    glue = " de " if generic_name.lower() in {"rotura", "distensión", "inflamación", "fisura", "luxación", "fractura", "sobrecarga", "contractura", "microrotura", "tendinitis"} else " en "
    return (generic_name + glue + zone_name)[:1].upper() + (generic_name + glue + zone_name)[1:]


def roll_match_injury(player: dict[str, Any], *, seed: int, game_date: date, previous_history: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Create one career injury from the MDB catalogue.

    Player injury proneness affects the severity distribution, while the source
    ``Frecuencia`` field only acts as a mild relative weight because the editor
    does not document an exact probability formula.
    """
    specific, generic, specific_zones, body_zones = _catalog_index()
    pid = int(player.get("source_id") or 0)
    proneness = max(0, min(3, int(player.get("injury_proneness") or 0)))
    rng = Random(int(seed) ^ pid * 104729 ^ game_date.toordinal() * 193)

    # Most football injuries are short/medium. Very long injuries exist but are
    # deliberately rare; source proneness increases their chance rather than
    # making every knock last longer.
    severe_chance = .008 + proneness * .012
    medium_chance = .28 + proneness * .035
    roll = rng.random()
    if roll < severe_chance:
        target_days = rng.randint(55, 150)
    elif roll < severe_chance + medium_chance:
        target_days = rng.randint(18, 45)
    else:
        target_days = rng.randint(5, 21)

    candidates: list[tuple[float, dict[str, Any]]] = []
    for row in specific:
        lo = max(1.0, float(row.get("Conv_min") or 1.0))
        hi = max(lo, float(row.get("Conv_max") or lo))
        midpoint = (lo + hi) / 2.0
        # Close duration + documented frequency is preferred. Frecuencia 0 is
        # still possible because it may mean uncommon, not impossible.
        frequency = max(1.0, 1.0 + float(row.get("Frecuencia") or 0) * .75)
        distance = abs(midpoint - target_days)
        weight = frequency / (1.0 + distance * .22)
        candidates.append((weight, row))
    if not candidates:
        return {
            "source_specific_id": None, "source_generic_id": None,
            "name": "Problemas físicos", "body_area": None, "laterality": None,
            "expected_days": target_days, "start": game_date.isoformat(),
            "expected_return": (game_date + timedelta(days=target_days)).isoformat(),
            "provenance": "career_generated_fallback",
        }
    rows = [row for _, row in candidates]
    weights = [weight for weight, _ in candidates]
    picked = rng.choices(rows, weights=weights, k=1)[0]
    injury_id = int(picked["Lesion"]); zone_id = int(picked["Zona"])
    generic_row = generic.get(injury_id) or {}
    zone_row = specific_zones.get(zone_id) or {}
    generic_zone = body_zones.get(int(zone_row.get("ZonaGenerica") or 0)) or {}
    lo = max(1, round(float(picked.get("Conv_min") or 1)))
    hi = max(lo, round(float(picked.get("Conv_max") or lo)))
    # Stay inside the source recovery range; proneness determines *what* injury
    # occurs, not a fictitious extension beyond the source definition.
    days = rng.randint(lo, hi)
    laterality = None
    if bool(generic_zone.get("Lateralidad")):
        laterality = rng.choice(["Derecha", "Izquierda"])
    history = previous_history or []
    recurrence = any(
        int(row.get("source_specific_id") or -1) == int(picked["ID"])
        or (row.get("body_area") and row.get("body_area") == zone_row.get("Nombre"))
        for row in history[-12:]
    )
    return {
        "source_specific_id": int(picked["ID"]),
        "source_generic_id": injury_id,
        "name": _label(generic_row.get("Nombre"), zone_row.get("Nombre")),
        "body_area": zone_row.get("Nombre") or generic_zone.get("Nombre"),
        "laterality": laterality,
        "expected_days": days,
        "days": days,
        "start": game_date.isoformat(),
        "expected_return": (game_date + timedelta(days=days)).isoformat(),
        "end": None,
        "recurrence": bool(recurrence),
        "operation_possible": bool(picked.get("Operacion")),
        "infiltrable": bool(picked.get("Infiltrable")),
        "source_frequency": int(picked.get("Frecuencia") or 0),
        "provenance": "career_generated_from_mdb_injury_catalog",
    }


def register_match_injury(dev_row: dict[str, Any], player: dict[str, Any], *, seed: int, game_date: date) -> dict[str, Any]:
    history = list(dev_row.get("injury_history") or [])
    injury = roll_match_injury(player, seed=seed, game_date=game_date, previous_history=history)
    dev_row["injury_days"] = max(int(dev_row.get("injury_days") or 0), int(injury["expected_days"]))
    dev_row["current_injury"] = dict(injury)
    history.append(dict(injury))
    dev_row["injury_history"] = history[-30:]
    return injury


def recover_medical_day(dev_row: dict[str, Any], *, game_date: date | None = None) -> None:
    previous = max(0, int(dev_row.get("injury_days") or 0))
    if previous <= 0:
        return
    remaining = previous - 1
    dev_row["injury_days"] = remaining
    current = dev_row.get("current_injury")
    if remaining == 0 and current:
        recovered_on = (game_date.isoformat() if game_date else current.get("expected_return"))
        current = {**current, "end": recovered_on, "recovered_on": recovered_on}
        history = list(dev_row.get("injury_history") or [])
        if history:
            history[-1] = {**history[-1], "end": recovered_on, "recovered_on": recovered_on}
        dev_row["injury_history"] = history[-30:]
        dev_row["current_injury"] = None


def medical_api(dev_row: dict[str, Any]) -> dict[str, Any]:
    days = max(0, int(dev_row.get("injury_days") or 0))
    current = dict(dev_row.get("current_injury") or {}) if days else None
    history = [dict(row) for row in (dev_row.get("injury_history") or [])]
    return {
        "status": "Lesionado" if days else "Disponible",
        "injury_days": days,
        "current_injury": current,
        "history": history,
    }


def medical_staff_report(
    dev_row: dict[str, Any], *, effectiveness: dict[str, Any], game_date: date, seed: int, player_id: int
) -> dict[str, Any]:
    """Career-facing medical information filtered through the responsible person."""
    base = medical_api(dev_row)
    quality = max(1, min(20, int(effectiveness.get("quality") or 10)))
    confidence = max(35, min(97, int(effectiveness.get("confidence") or (38 + quality * 3))))
    radius = 1 if quality >= 17 else 2 if quality >= 14 else 4 if quality >= 11 else 7
    days = max(0, int(base.get("injury_days") or 0))
    current = dict(base.get("current_injury") or {}) if days else None
    if current:
        rng = Random(int(seed) ^ int(player_id) * 31337 ^ game_date.toordinal())
        center = max(0, days + (0 if quality >= 17 else rng.randint(-max(1, radius // 2), max(1, radius // 2))))
        lo = max(0, center - radius); hi = max(lo, center + radius)
        current["estimated_days_range"] = [lo, hi]
        current["estimated_return_from"] = (game_date + timedelta(days=lo)).isoformat()
        current["estimated_return_to"] = (game_date + timedelta(days=hi)).isoformat()
        if quality < 17:
            current.pop("expected_return", None)
        recommendation = (
            "No disponible; priorizar recuperación." if days > 7 else
            "Valorar reintegración progresiva cuando complete la recuperación." if days > 0 else
            "Disponible para carga normal."
        )
    else:
        risk = max(0, min(100, int(dev_row.get("injury_risk") or 0)))
        load = max(0, min(100, int(dev_row.get("training_load") or 0)))
        condition = max(0, min(100, int(dev_row.get("condition") or 100)))
        if risk >= 70 or condition <= 62:
            recommendation = "Disponible, pero con riesgo alto: reducir carga y evitar forzar."
        elif risk >= 52 or load >= 48:
            recommendation = "Disponible con vigilancia de carga; conviene dosificar."
        else:
            recommendation = "Disponible para carga normal."
    return {
        **base,
        "current_injury": current,
        "workload": {
            "condition": max(0, min(100, int(dev_row.get("condition") or 100))),
            "training_load": max(0, min(100, int(dev_row.get("training_load") or 0))),
            "fatigue": max(0, min(100, int(dev_row.get("fatigue") or 0))),
            "injury_risk": max(0, min(100, int(dev_row.get("injury_risk") or 0))),
        },
        "assessment": {
            "responsible": str(effectiveness.get("assignee_name") or "Cuerpo médico"),
            "responsible_role": str(effectiveness.get("assignee_role") or "Responsable médico"),
            "quality": quality, "quality_label": str(effectiveness.get("quality_label") or "—"),
            "confidence": confidence, "uncertainty_days": radius if days else 0,
            "recommendation": recommendation,
        },
    }
